// <auto-generated />
using System;
using BusBookingWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusBookingWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027094850_Seed20BusesWithFixedDates")]
    partial class Seed20BusesWithFixedDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BusBookingWebApp.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatsBooked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusType = "Sleeper",
                            Name = "Bus 1",
                            RegistrationNumber = "MH12AB1001",
                            RouteId = 2,
                            TotalSeats = 45
                        },
                        new
                        {
                            Id = 2,
                            BusType = "Seater",
                            Name = "Bus 2",
                            RegistrationNumber = "MH12AB1002",
                            RouteId = 3,
                            TotalSeats = 50
                        },
                        new
                        {
                            Id = 3,
                            BusType = "Sleeper",
                            Name = "Bus 3",
                            RegistrationNumber = "MH12AB1003",
                            RouteId = 4,
                            TotalSeats = 55
                        },
                        new
                        {
                            Id = 4,
                            BusType = "Seater",
                            Name = "Bus 4",
                            RegistrationNumber = "MH12AB1004",
                            RouteId = 5,
                            TotalSeats = 60
                        },
                        new
                        {
                            Id = 5,
                            BusType = "Sleeper",
                            Name = "Bus 5",
                            RegistrationNumber = "MH12AB1005",
                            RouteId = 1,
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 6,
                            BusType = "Seater",
                            Name = "Bus 6",
                            RegistrationNumber = "MH12AB1006",
                            RouteId = 2,
                            TotalSeats = 45
                        },
                        new
                        {
                            Id = 7,
                            BusType = "Sleeper",
                            Name = "Bus 7",
                            RegistrationNumber = "MH12AB1007",
                            RouteId = 3,
                            TotalSeats = 50
                        },
                        new
                        {
                            Id = 8,
                            BusType = "Seater",
                            Name = "Bus 8",
                            RegistrationNumber = "MH12AB1008",
                            RouteId = 4,
                            TotalSeats = 55
                        },
                        new
                        {
                            Id = 9,
                            BusType = "Sleeper",
                            Name = "Bus 9",
                            RegistrationNumber = "MH12AB1009",
                            RouteId = 5,
                            TotalSeats = 60
                        },
                        new
                        {
                            Id = 10,
                            BusType = "Seater",
                            Name = "Bus 10",
                            RegistrationNumber = "MH12AB1010",
                            RouteId = 1,
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 11,
                            BusType = "Sleeper",
                            Name = "Bus 11",
                            RegistrationNumber = "MH12AB1011",
                            RouteId = 2,
                            TotalSeats = 45
                        },
                        new
                        {
                            Id = 12,
                            BusType = "Seater",
                            Name = "Bus 12",
                            RegistrationNumber = "MH12AB1012",
                            RouteId = 3,
                            TotalSeats = 50
                        },
                        new
                        {
                            Id = 13,
                            BusType = "Sleeper",
                            Name = "Bus 13",
                            RegistrationNumber = "MH12AB1013",
                            RouteId = 4,
                            TotalSeats = 55
                        },
                        new
                        {
                            Id = 14,
                            BusType = "Seater",
                            Name = "Bus 14",
                            RegistrationNumber = "MH12AB1014",
                            RouteId = 5,
                            TotalSeats = 60
                        },
                        new
                        {
                            Id = 15,
                            BusType = "Sleeper",
                            Name = "Bus 15",
                            RegistrationNumber = "MH12AB1015",
                            RouteId = 1,
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 16,
                            BusType = "Seater",
                            Name = "Bus 16",
                            RegistrationNumber = "MH12AB1016",
                            RouteId = 2,
                            TotalSeats = 45
                        },
                        new
                        {
                            Id = 17,
                            BusType = "Sleeper",
                            Name = "Bus 17",
                            RegistrationNumber = "MH12AB1017",
                            RouteId = 3,
                            TotalSeats = 50
                        },
                        new
                        {
                            Id = 18,
                            BusType = "Seater",
                            Name = "Bus 18",
                            RegistrationNumber = "MH12AB1018",
                            RouteId = 4,
                            TotalSeats = 55
                        },
                        new
                        {
                            Id = 19,
                            BusType = "Sleeper",
                            Name = "Bus 19",
                            RegistrationNumber = "MH12AB1019",
                            RouteId = 5,
                            TotalSeats = 60
                        },
                        new
                        {
                            Id = 20,
                            BusType = "Seater",
                            Name = "Bus 20",
                            RegistrationNumber = "MH12AB1020",
                            RouteId = 1,
                            TotalSeats = 40
                        });
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistanceKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanceKm = 150,
                            From = "Mumbai",
                            To = "Pune"
                        },
                        new
                        {
                            Id = 2,
                            DistanceKm = 200,
                            From = "Pune",
                            To = "Nashik"
                        },
                        new
                        {
                            Id = 3,
                            DistanceKm = 185,
                            From = "Nashik",
                            To = "Aurangabad"
                        },
                        new
                        {
                            Id = 4,
                            DistanceKm = 335,
                            From = "Mumbai",
                            To = "Aurangabad"
                        },
                        new
                        {
                            Id = 5,
                            DistanceKm = 230,
                            From = "Pune",
                            To = "Aurangabad"
                        });
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fare")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2025, 10, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 1,
                            DepartureTime = new DateTime(2025, 10, 22, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 400m
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2025, 10, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 2,
                            DepartureTime = new DateTime(2025, 10, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 410m
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2025, 10, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 3,
                            DepartureTime = new DateTime(2025, 10, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 420m
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(2025, 10, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 4,
                            DepartureTime = new DateTime(2025, 10, 22, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 430m
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2025, 10, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 5,
                            DepartureTime = new DateTime(2025, 10, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 440m
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = new DateTime(2025, 10, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 6,
                            DepartureTime = new DateTime(2025, 10, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 450m
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = new DateTime(2025, 10, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 7,
                            DepartureTime = new DateTime(2025, 10, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 460m
                        },
                        new
                        {
                            Id = 8,
                            ArrivalTime = new DateTime(2025, 10, 22, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 8,
                            DepartureTime = new DateTime(2025, 10, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 470m
                        },
                        new
                        {
                            Id = 9,
                            ArrivalTime = new DateTime(2025, 10, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 9,
                            DepartureTime = new DateTime(2025, 10, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 480m
                        },
                        new
                        {
                            Id = 10,
                            ArrivalTime = new DateTime(2025, 10, 22, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 10,
                            DepartureTime = new DateTime(2025, 10, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 490m
                        },
                        new
                        {
                            Id = 11,
                            ArrivalTime = new DateTime(2025, 10, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 11,
                            DepartureTime = new DateTime(2025, 10, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 500m
                        },
                        new
                        {
                            Id = 12,
                            ArrivalTime = new DateTime(2025, 10, 22, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 12,
                            DepartureTime = new DateTime(2025, 10, 22, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 510m
                        },
                        new
                        {
                            Id = 13,
                            ArrivalTime = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 13,
                            DepartureTime = new DateTime(2025, 10, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 520m
                        },
                        new
                        {
                            Id = 14,
                            ArrivalTime = new DateTime(2025, 10, 23, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 14,
                            DepartureTime = new DateTime(2025, 10, 22, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 530m
                        },
                        new
                        {
                            Id = 15,
                            ArrivalTime = new DateTime(2025, 10, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 15,
                            DepartureTime = new DateTime(2025, 10, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 540m
                        },
                        new
                        {
                            Id = 16,
                            ArrivalTime = new DateTime(2025, 10, 23, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 16,
                            DepartureTime = new DateTime(2025, 10, 22, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 550m
                        },
                        new
                        {
                            Id = 17,
                            ArrivalTime = new DateTime(2025, 10, 23, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 17,
                            DepartureTime = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 560m
                        },
                        new
                        {
                            Id = 18,
                            ArrivalTime = new DateTime(2025, 10, 23, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 18,
                            DepartureTime = new DateTime(2025, 10, 23, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 570m
                        },
                        new
                        {
                            Id = 19,
                            ArrivalTime = new DateTime(2025, 10, 23, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 19,
                            DepartureTime = new DateTime(2025, 10, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 580m
                        },
                        new
                        {
                            Id = 20,
                            ArrivalTime = new DateTime(2025, 10, 23, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 20,
                            DepartureTime = new DateTime(2025, 10, 23, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Fare = 590m
                        });
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Seat", b =>
                {
                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.HasKey("BusId", "SeatNumber");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("BusBookingWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Booking", b =>
                {
                    b.HasOne("BusBookingWebApp.Models.Schedule", "Schedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusBookingWebApp.Models.User", null)
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Bus", b =>
                {
                    b.HasOne("BusBookingWebApp.Models.Route", "Route")
                        .WithMany("Buses")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Schedule", b =>
                {
                    b.HasOne("BusBookingWebApp.Models.Bus", "Bus")
                        .WithMany("Schedules")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Seat", b =>
                {
                    b.HasOne("BusBookingWebApp.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Bus", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Route", b =>
                {
                    b.Navigation("Buses");
                });

            modelBuilder.Entity("BusBookingWebApp.Models.Schedule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BusBookingWebApp.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
